//下载代码，构建镜像，放入私仓,  强制下载新镜像，marathon重启docker相关任务
node{
    stage('get checkout'){
       //checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'CleanCheckout'], [$class: 'CleanBeforeCheckout']], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'oras903', url: 'https://github.com/oras903/haproxy_reload.git']]])
       
          checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'CleanBeforeCheckout']], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'oras903', url: 'https://github.com/oras903/haproxy_reload.git']]])
          dir('src/main') {
              withDockerRegistry([url: 'http://192.168.20.10:31076']) {

              def customImage = docker.build("192.168.20.10:31076/haproxy_reload:${env.BUILD_ID}")

              customImage.push('latest') 
              }
          }
      
    }


    stage('deploy'){
        //执行部署脚本
        echo "deploy ......" 
        //marathon_url="http://192.168.20.10:8088"
        //marathon docker: '192.168.20.10:31076/haproxy_reload', dockerForcePull: true, forceUpdate: true, url: marathon_url, filename: "haproxy_reload.json"
    withDockerRegistry([url: 'http://192.168.20.10:31076']) {

        marathon credentialsId: '', docker: '192.168.20.10:31076/haproxy_reload:latest', dockerForcePull: true, filename: 'src/main/haproxy_reload.json', forceUpdate: true, id: 'haproxy_reload', url: 'http://192.168.20.11:8088'
    }
    }
}
